#!/bin/sh
# Update UFO after any edits other than with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo
echo "Normalizing UFOs..."
psfnormalize -p checkfix=fix source/masters/*-Regular.ufo  &
wait

echo
echo "Updating woff metadata xml file..."
psfmakewoffmetadata -q -n DoulosSILCipher -i org.sil.fonts source/masters/*-Regular.ufo -o "source/DoulosSILCipher-WOFF-metadata.xml"

echo
echo "Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none -p backup=False --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/*.designspace

# echo
echo "Building internal fea..."
# makefea -o source/masters/DoulosSILCipher-Regular.ufo/features.fea -l source/logs/DoulosSILCipher-Regular-makefea.log -i source/opentype/main.feax --ignoreglyphs --omitaps "R, O" source/masters/DoulosSILCipher-Regular.ufo &


wait

echo
echo "preflight completed!"
